# Generated by Django 6.0.2 on 2026-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_job_logo_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_top_company',
            field=models.BooleanField(default=False),
        ),
    ]
