# Generated by Django 5.2 on 2026-03-03 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_company_is_top_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='current_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='expected_ctc',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='total_experience_years',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(default='Job Seeker', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_read_receipts', models.BooleanField(default=True)),
                ('restrict_duplicate_applications', models.BooleanField(default=False)),
                ('hide_cv', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
