# Generated by Django 5.2 on 2026-03-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_company_is_verified_companyverification'),
        ('jobapp', '0013_job_job_status_alter_job_experience_required'),
    ]

    operations = [
    ]
